### ISSUE TITLE
Support arbitary epub or pdf?

### ISSUE THREAD

**Issue by samuk** [elimu-ai/vitabu#91]
Hi I like this app. Is there a way to configure it to access .epubs or .pdf's on a given path?

My kids books are all in a folder on external sd. I'd like a folder browser so my users (parents) can configure the app to use that path once and then it can load all the books under that path/folder.

This is the current content https://rosettaphone.org/ although I plan to upgrade the kids sections to use https://digitallibrary.io/ content

**Comment by nya-elimuai** [comment]
Hi, @samuk. No, this storybook app does not load `.epub` files directly. Instead, the way it works is that we upload `.epub` files to our webapp where they are converted into our own custom [storage format](https://github.com/elimu-ai/model/blob/master/src/main/java/ai/elimu/model/v2/gson/content/StoryBookGson.java). And from there, the storybooks are downloaded to Android devices.

See how `Vitabu` fits into the software architecture here: https://github.com/elimu-ai/wiki/blob/master/SOFTWARE_ARCHITECTURE.md#learning-platform

We do it this way because it makes it easier to clean up and improve ePUB storybooks that have been wrongly formatted/translated, etc. Also, this way makes it easier to collect learning analytics on how the children are interacting with content inside each book. And recording word-by-word highlighting while playing audio recordings becomes easier when having freedom to edit the content and source code of each book (although [SMIL](http://idpf.org/epub/30/spec/epub30-mediaoverlays.html) should theoretically work with original ePUB files as well).

**Comment by samuk** [comment]
OK that does sound reasoable. Although the epubs from https://digitallibrary.io/  are already good quality, so you could just use those. 

I'm reluctant to use the rest of your ecosystem at this time as the other apps seem buggy/incomplete. I'll see if I can find the time up upload some digital library content to your webapp to test how that works.

**Comment by nya-elimuai** [comment]
@samuk If you are looking for a user-friendly Android app for reading ePUB books, here is a good one: https://play.google.com/store/apps/details?id=com.faultexception.reader

**Comment by samuk** [comment]
Thanks. It doesn't seem to be FOSS though. I need that to redistribute.

Using https://f-droid.org/en/packages/com.foobnix.pro.pdf.reader/ It  
has TTS/ read aloud & nice reflow for PDF. It's a little  
overcomplicated though.




Quoting Nya Ξlimu ***@***.***>:
